<a href="https://colab.research.google.com/github/LeilaYK/Classifying_Shapes/blob/main/%EC%9D%B4%EB%AF%B8%EC%A7%80_%EB%B6%80%ED%92%80%EB%A6%AC%EA%B8%B0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Flatten
from keras.layers.convolutional import Conv2D
from keras.layers.convolutional import MaxPooling2D
from keras.preprocessing.image import ImageDataGenerator

In [ ]:
np.random.seed(6)

In [ ]:
train_datagen = ImageDataGenerator(rescale=1./255)

train_generator = train_datagen.flow_from_directory(
        './drive/MyDrive/shapes2/train',
        target_size=(128, 128),
        batch_size=10,
        class_mode='categorical')

test_datagen = ImageDataGenerator(rescale=1./255)

test_generator = test_datagen.flow_from_directory(
        './drive/MyDrive/shapes2/test',
        target_size=(128, 128),    
        batch_size=10,
        class_mode='categorical')

Found 240 images belonging to 3 classes.
Found 60 images belonging to 3 classes.


In [ ]:
model = Sequential()
model.add(Conv2D(32, kernel_size=(3, 3),
                 activation='relu',
                 input_shape=(128,128,3)))
model.add(Conv2D(64, (3, 3), activation='relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Flatten())
model.add(Dense(128, activation='relu'))
model.add(Dense(3, activation='softmax'))

In [ ]:
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

In [ ]:
# model.fit_generator(
#         train_generator,
#         steps_per_epoch=24,
#         epochs=50,
#         validation_data=test_generator,
#         validation_steps=6)

/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/training.py:1844: UserWarning: `Model.fit_generator` is deprecated and will be removed in a future version. Please use `Model.fit`, which supports generators.
  warnings.warn('`Model.fit_generator` is deprecated and '


Epoch 1/50
24/24 [==============================] - 2s 57ms/step - loss: 11.8106 - accuracy: 0.4012 - val_loss: 1.0935 - val_accuracy: 0.3667
Epoch 2/50
24/24 [==============================] - 1s 51ms/step - loss: 1.0887 - accuracy: 0.4960 - val_loss: 1.0811 - val_accuracy: 0.4833
Epoch 3/50
24/24 [==============================] - 1s 51ms/step - loss: 0.9168 - accuracy: 0.7258 - val_loss: 1.3793 - val_accuracy: 0.3333
Epoch 4/50
24/24 [==============================] - 1s 51ms/step - loss: 0.5317 - accuracy: 0.7703 - val_loss: 1.3241 - val_accuracy: 0.4667
Epoch 5/50
24/24 [==============================] - 1s 52ms/step - loss: 0.1733 - accuracy: 0.9926 - val_loss: 2.0486 - val_accuracy: 0.4167
Epoch 6/50
24/24 [==============================] - 1s 49ms/step - loss: 0.0134 - accuracy: 1.0000 - val_loss: 2.5631 - val_accuracy: 0.3500
Epoch 7/50
24/24 [==============================] - 1s 50ms/step - loss: 0.0063 - accuracy: 1.0000 - val_loss: 2.9464 - val_accuracy: 0.3333
Epoch 8/50
2

In [ ]:
print("-- Evaluate --")
scores = model.evaluate_generator(test_generator, steps=5)
print("%s: %.2f%%" %(model.metrics_names[1], scores[1]*100))

-- Evaluate --


/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/training.py:1877: UserWarning: `Model.evaluate_generator` is deprecated and will be removed in a future version. Please use `Model.evaluate`, which supports generators.
  warnings.warn('`Model.evaluate_generator` is deprecated and '


accuracy: 40.00%


In [ ]:
print("-- Predict --")
output = model.predict_generator(test_generator, steps=5)
np.set_printoptions(formatter={'float': lambda x: "{0:0.3f}".format(x)})
print(test_generator.class_indices)
print(output)

-- Predict --


/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/training.py:1905: UserWarning: `Model.predict_generator` is deprecated and will be removed in a future version. Please use `Model.predict`, which supports generators.
  warnings.warn('`Model.predict_generator` is deprecated and '


{'circle': 0, 'square': 1, 'triangle': 2}
[[0.002 0.998 0.000]
 [0.001 0.000 0.999]
 [0.705 0.074 0.222]
 [0.000 1.000 0.000]
 [0.075 0.022 0.903]
 [0.000 0.000 1.000]
 [0.000 0.002 0.998]
 [0.999 0.000 0.001]
 [1.000 0.000 0.000]
 [0.038 0.000 0.962]
 [1.000 0.000 0.000]
 [0.001 0.005 0.994]
 [0.000 0.648 0.352]
 [0.000 0.218 0.782]
 [0.000 1.000 0.000]
 [0.019 0.981 0.000]
 [0.000 0.000 1.000]
 [0.000 0.000 1.000]
 [0.008 0.000 0.992]
 [1.000 0.000 0.000]
 [1.000 0.000 0.000]
 [0.764 0.039 0.197]
 [0.000 0.000 1.000]
 [0.544 0.023 0.433]
 [0.067 0.468 0.465]
 [0.000 1.000 0.000]
 [0.004 0.996 0.000]
 [0.994 0.000 0.006]
 [0.699 0.298 0.003]
 [0.784 0.080 0.136]
 [0.700 0.017 0.283]
 [0.009 0.013 0.978]
 [0.103 0.126 0.771]
 [0.983 0.017 0.000]
 [0.000 0.000 1.000]
 [0.020 0.062 0.918]
 [1.000 0.000 0.000]
 [0.950 0.000 0.049]
 [0.086 0.147 0.766]
 [0.842 0.158 0.000]
 [0.257 0.743 0.000]
 [0.995 0.000 0.005]
 [0.000 0.260 0.740]
 [0.951 0.048 0.002]
 [0.000 0.483 0.517]
 [0.718 0.279

In [ ]:
from keras.preprocessing.image import ImageDataGenerator

# 데이터셋 불러오기
train_datagen = ImageDataGenerator(rescale=1./255, 
                                   rotation_range=10,
                                   width_shift_range=0.2,
                                   height_shift_range=0.2,
                                   shear_range=0.7,
                                   zoom_range=[0.9, 2.2],
                                   horizontal_flip=True,
                                   vertical_flip=True,
                                   fill_mode='nearest')

train_generator = train_datagen.flow_from_directory(
        './drive/MyDrive/shapes2/train',
        target_size=(128, 128),
        batch_size=10,
        class_mode='categorical')

test_datagen = ImageDataGenerator(rescale=1./255)

test_generator = test_datagen.flow_from_directory(
        './drive/MyDrive/shapes2/test',
        target_size=(128, 128),    
        batch_size=10,
        class_mode='categorical')

from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Flatten
from keras.layers.convolutional import Conv2D
from keras.layers.convolutional import MaxPooling2D

from keras.layers import Dropout

model = Sequential()
model.add(Conv2D(32, kernel_size=(3, 3),
                 activation='relu',
                 input_shape=(128,128,3)))
model.add(Conv2D(64, (3, 3), activation='relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Flatten())
model.add(Dense(128, activation='relu'))
model.add(Dense(3, activation='softmax'))

# 모델 엮기
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])



Found 240 images belonging to 3 classes.
Found 60 images belonging to 3 classes.


In [ ]:
# 모델 학습시키기
model.fit_generator(
        train_generator,
        steps_per_epoch= 5 ,
        epochs= 1000,
        validation_data=test_generator,
        validation_steps=6)

# 모델 평가하기
print("-- Evaluate --")

scores = model.evaluate_generator(
            test_generator, 
            steps = 5)

print("%s: %.2f%%" %(model.metrics_names[1], scores[1]*100))

# 모델 예측하기
print("-- Predict --")

output = model.predict_generator(
            test_generator, 
            steps = 5)

np.set_printoptions(formatter={'float': lambda x: "{0:0.3f}".format(x)})

print(output)

Epoch 1/1000
1/5 [=====>........................] - ETA: 0s - loss: 1.0919 - accuracy: 0.6000

/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/training.py:1844: UserWarning: `Model.fit_generator` is deprecated and will be removed in a future version. Please use `Model.fit`, which supports generators.
  warnings.warn('`Model.fit_generator` is deprecated and '


5/5 [==============================] - 1s 164ms/step - loss: 1.0957 - accuracy: 0.4400 - val_loss: 1.0995 - val_accuracy: 0.3333
Epoch 2/1000
5/5 [==============================] - 1s 143ms/step - loss: 1.1022 - accuracy: 0.2200 - val_loss: 1.0994 - val_accuracy: 0.3333
Epoch 3/1000
5/5 [==============================] - 1s 146ms/step - loss: 1.1010 - accuracy: 0.2600 - val_loss: 1.0992 - val_accuracy: 0.3333
Epoch 4/1000
5/5 [==============================] - 1s 145ms/step - loss: 1.0984 - accuracy: 0.3400 - val_loss: 1.0989 - val_accuracy: 0.3333
Epoch 5/1000
5/5 [==============================] - 1s 149ms/step - loss: 1.1005 - accuracy: 0.2400 - val_loss: 1.0986 - val_accuracy: 0.3000
Epoch 6/1000
5/5 [==============================] - 1s 154ms/step - loss: 1.0971 - accuracy: 0.3200 - val_loss: 1.2016 - val_accuracy: 0.3333
Epoch 7/1000
5/5 [==============================] - 1s 148ms/step - loss: 1.1105 - accuracy: 0.3600 - val_loss: 1.0967 - val_accuracy: 0.3667
Epoch 8/1000
5/5 [=

/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/training.py:1877: UserWarning: `Model.evaluate_generator` is deprecated and will be removed in a future version. Please use `Model.evaluate`, which supports generators.
  warnings.warn('`Model.evaluate_generator` is deprecated and '


accuracy: 58.00%
-- Predict --


/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/training.py:1905: UserWarning: `Model.predict_generator` is deprecated and will be removed in a future version. Please use `Model.predict`, which supports generators.
  warnings.warn('`Model.predict_generator` is deprecated and '


[[1.000 0.000 0.000]
 [0.782 0.036 0.183]
 [0.000 0.920 0.079]
 [0.997 0.001 0.002]
 [1.000 0.000 0.000]
 [0.000 0.999 0.000]
 [0.560 0.362 0.078]
 [0.972 0.028 0.000]
 [0.000 0.927 0.073]
 [1.000 0.000 0.000]
 [1.000 0.000 0.000]
 [1.000 0.000 0.000]
 [0.000 0.913 0.087]
 [0.081 0.547 0.371]
 [0.000 0.908 0.091]
 [0.002 0.898 0.100]
 [1.000 0.000 0.000]
 [0.069 0.279 0.652]
 [0.656 0.213 0.131]
 [0.204 0.167 0.629]
 [0.852 0.087 0.061]
 [0.003 0.970 0.028]
 [0.001 0.879 0.120]
 [0.001 0.959 0.040]
 [1.000 0.000 0.000]
 [0.530 0.261 0.208]
 [0.000 0.957 0.043]
 [0.000 0.987 0.013]
 [0.999 0.000 0.001]
 [0.965 0.028 0.008]
 [0.000 0.998 0.002]
 [0.000 0.981 0.019]
 [0.084 0.625 0.291]
 [0.816 0.029 0.155]
 [1.000 0.000 0.000]
 [1.000 0.000 0.000]
 [0.000 0.992 0.008]
 [0.005 0.956 0.039]
 [0.000 1.000 0.000]
 [0.001 0.964 0.035]
 [0.000 0.998 0.002]
 [0.265 0.245 0.490]
 [0.000 1.000 0.000]
 [0.000 1.000 0.000]
 [0.536 0.302 0.163]
 [0.816 0.143 0.040]
 [0.068 0.600 0.332]
 [1.000 0.000